spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: workflow-service
          uri: http://localhost:8082
          predicates:
            - Path=/workflow/**
        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/products/**
        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/users/**
  reactor:
    context-propagation: AUTO

server:
  port: 8081

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      produce: w3c
      consume: w3c
  endpoints:
    web:
      exposure:
        include: health,info
