spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: workflow-service
          uri: ${WORKFLOW_SERVICE_URL}
          predicates:
            - Path=/workflow/**

  reactor:
    context-propagation: AUTO

server:
  port: ${API_GATEWAY_SERVICE_PORT}

management:
  tracing:
    enabled: true
    sampling:
      probability: ${MANAGEMENT_SAMPLING_PROBABILITY}
    propagation:
      produce: w3c
      consume: w3c
  endpoints:
    web:
      exposure:
        include: health,info
