management:
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_TRACING_ENDPOINT}
      transport: HTTP

otel:
  resource:
    attributes:
      service.name: ${spring.application.name}
      service.namespace: ${SERVICE_NAMESPACE}
      deployment.environment: dev