spring:
  application:
    name: workflow-service

services:
  order-service:
    url: http://localhost:8083
  product-service:
    url: http://localhost:8084
  user-service:
    url: http://localhost:8085

server:
  port: 8082

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% for local/dev
    propagation:
      produce: w3c
      consume: w3c

#
#  otlp:
#    tracing:
#      endpoint: "http://otel-collector.istio-system:4317"   # later Istio OTEL collector
