spring:
  application:
    name: workflow-service

services:
  order-service:
    url: http://localhost:8083
  product-service:
    url: http://localhost:8084
  user-service:
    url: http://localhost:8085

server:
  port: 8082