spring:
  application:
    name: workflow-service

services:
  order-service:
    url: ${ORDER_SERVICE_URL}
  product-service:
    url: ${PRODUCT_SERVICE_URL}
  user-service:
    url: ${USER_SERVICE_URL}

server:
  port: ${WORKFLOW_SERVICE_PORT}

management:
  tracing:
    enabled: true
    sampling:
      probability: ${MANAGEMENT_SAMPLING_PROBABILITY}
    propagation:
      produce: w3c
      consume: w3c
