spring:
  application:
    name: productName-service
  datasource:
    url: jdbc:postgresql://localhost:5432/oms
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

server:
  port: 8084

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% for local/dev
    propagation:
      produce: w3c
      consume: w3c
#
#  otlp:
#    tracing:
#      endpoint: "http://otel-collector.istio-system:4317"   # later Istio OTEL collector
